"""expand_invite_codes

Revision ID: d3923a929279
Revises: c38cec37d637
Create Date: 2026-03-01 10:57:38.894845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3923a929279'
down_revision = 'c38cec37d637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('role', sa.String(), nullable=False))
    op.add_column('invites', sa.Column('max_uses', sa.Integer(), nullable=True))
    op.add_column('invites', sa.Column('uses_count', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('invites_used_by_fkey'), 'invites', type_='foreignkey')
    op.drop_column('invites', 'used_by')
    op.drop_column('invites', 'used_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invites', sa.Column('used_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('invites_used_by_fkey'), 'invites', 'users', ['used_by'], ['id'])
    op.drop_column('invites', 'uses_count')
    op.drop_column('invites', 'max_uses')
    op.drop_column('invites', 'role')
    # ### end Alembic commands ###
